name: holoviz_ocean_tut
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.7
  - hvplot
  - holoviews
  - geoviews>1.7.0
  - datashader
  - panel>=0.11.3
  - pyproj
  - param
  - colorcet
  - jupyterlab=2
  - xarray
  - pandas
